// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
	proto.RegisterType((*Token)(nil), "go.micro.srv.user.Token")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x6d, 0x37, 0x5d, 0xeb, 0x2c, 0x08, 0x0e, 0x8a, 0x61, 0xbd, 0x2c, 0x3d, 0x09, 0x62,
	0x84, 0xdd, 0xa3, 0x20, 0x88, 0x6f, 0x50, 0xf5, 0x01, 0x62, 0x3b, 0x6a, 0x70, 0xdb, 0x94, 0xa4,
	0x5b, 0xf1, 0x15, 0x7c, 0x6a, 0xc9, 0x44, 0xf7, 0xe2, 0x76, 0x2f, 0xed, 0x7c, 0xff, 0x3f, 0xc9,
	0xfc, 0x43, 0xe0, 0xac, 0x73, 0xb6, 0xb7, 0x37, 0x1b, 0x4f, 0x8e, 0x3f, 0x8a, 0x19, 0x4f, 0xde,
	0xac, 0x6a, 0x4c, 0xe5, 0xac, 0xf2, 0x6e, 0x50, 0xc1, 0x28, 0x06, 0x10, 0xcf, 0x9e, 0x1c, 0x1e,
	0x43, 0x6a, 0x6a, 0x99, 0x2c, 0x92, 0xcb, 0xa3, 0x32, 0x35, 0x35, 0x22, 0x88, 0x56, 0x37, 0x24,
	0x53, 0x56, 0xb8, 0x46, 0x09, 0x87, 0x95, 0x6d, 0x3a, 0xdd, 0x7e, 0xc9, 0x09, 0xcb, 0x7f, 0x88,
	0xa7, 0x90, 0x51, 0xa3, 0xcd, 0x5a, 0x0a, 0xd6, 0x23, 0xe0, 0x1c, 0xf2, 0x4e, 0x7b, 0xff, 0x69,
	0x5d, 0x2d, 0x33, 0x36, 0xb6, 0x5c, 0xbc, 0x42, 0x5e, 0x92, 0xef, 0x6c, 0xeb, 0x09, 0xaf, 0x40,
	0x84, 0x2c, 0x3c, 0x7d, 0xb6, 0x3c, 0x57, 0xff, 0x52, 0xaa, 0x10, 0xb1, 0xe4, 0x26, 0xbc, 0x86,
	0x2c, 0xfc, 0xbd, 0x4c, 0x17, 0x93, 0x7d, 0xdd, 0xb1, 0xab, 0x58, 0x41, 0xf6, 0x64, 0x3f, 0xa8,
	0x0d, 0x11, 0xfb, 0x50, 0xfc, 0xee, 0x18, 0x21, 0xa8, 0x83, 0x5e, 0x9b, 0x9a, 0xf7, 0xcc, 0xcb,
	0x08, 0xcb, 0xef, 0x04, 0x66, 0xe1, 0x92, 0x47, 0x72, 0x83, 0xa9, 0x08, 0xef, 0x60, 0xfa, 0xe0,
	0x48, 0xf7, 0x84, 0x63, 0xe3, 0xe6, 0x17, 0x3b, 0x8c, 0xed, 0x82, 0xb7, 0x20, 0xee, 0x37, 0xfd,
	0xfb, 0xf8, 0x69, 0xb9, 0xc3, 0xe0, 0xd8, 0xc5, 0xc1, 0xcb, 0x94, 0xdf, 0x6e, 0xf5, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0xd0, 0x7c, 0x75, 0xd4, 0x01, 0x00, 0x00,
}
