version: "3"

services:
    server:
        build: ./consignment-service 
        environment:
            MICRO_REGISTRY: "mdns"
    
    client:
        build: ./consignment-client
        environment: 
            MICRO_REGISTRY: "mdns"