version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/farhansajid1/go-micro-project
    steps:
      - checkout
      - run:
          name: Build image
          command: ./.circleci/build.sh


        
