apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: farhansajid2/user-service:13df99ac837b4c1f34b516efcecf8111705eb350
        env:
          - name: PGUSER
            value: postgres
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            value: postgres_password
          - name: PGHOST
            value: postgres-cluster-ip
          - name: K8S
            value: "true"
        ports:
        - containerPort: 8080
        command: ["./main, "--selector=static"]

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8080
    targetPort: 8080

