apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: farhansajid2/web-server:13df99ac837b4c1f34b516efcecf8111705eb350
        ports:
        - containerPort: 8990
        command: ["./main", "--server_address=0.0.0.0:8080"]
        env:
          - name: APIHOST
            value: micro-service
          - name: K8S
            value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
  - port: 8990
    targetPort: 8990

