FROM golang as builder
WORKDIR /go/src/github.com/farhansajid1/go-micro-project/
COPY ./ /go/src/github.com/farhansajid1/go-micro-project/

RUN go get ./ # build the dependencies
RUN go build -o main

RUN chmod +x main

FROM alpine:latest
WORKDIR /app
COPY --from=builder /go/src/github.com/farhansajid1/go-docker/ /app/
CMD ./main

EXPOSE 8080
