FROM golang as builder
COPY ./ /go/src/github.com/farhansajid1/go-micro-project
WORKDIR /go/src/github.com/farhansajid1/go-micro-project/consignment-client

RUN go get ./ # build the dependencies
RUN go build -o main

RUN chmod +x main

FROM alpine:latest
WORKDIR /app
COPY --from=builder /go/src/github.com/farhansajid1/go-micro-project/consignment-client /app/
CMD ./main

EXPOSE 8080
